apiVersion: v1
kind: Service
metadata:
  name: wordpress2
  labels:
    app: wordpress2
spec:
  ports:
    - port: 80
  selector:
    app: wordpress2
    tier: frontend
  type: LoadBalancer
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wp2-pv-claim
  labels:
    app: wordpress2
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress2
  labels:
    greymatter.io/cluster: wordpress
    app: wordpress2
spec:
  selector:
    matchLabels:
      greymatter.io/cluster: wordpress
      app: wordpress2
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        greymatter.io/cluster: wordpress
        app: wordpress2
        tier: frontend
    spec:
      containers:
      - image: wordpress:4.8-apache
        name: wordpress2
        env:
        - name: WORDPRESS_DB_HOST
          value: wordpress-mysql
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password
        ports:
        - containerPort: 80
          name: wordpress
        volumeMounts:
        - name: wordpress2-persistent-storage
          mountPath: /var/www/html
      volumes:
      - name: wordpress2-persistent-storage
        persistentVolumeClaim:
          claimName: wp2-pv-claim
