apiVersion: v1
kind: Service
metadata:
  name: wordpressnew
  labels:
    app: wordpressnew
spec:
  ports:
    - port: 80
  selector:
    app: wordpressnew
    tier: frontend
  type: LoadBalancer
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wp-new-pv-claim
  labels:
    app: wordpressnew
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpressnew
  labels:
    greymatter.io/cluster: wordpressnew
    app: wordpressnew
  annotations:
    greymatter.io/egress-http-local: '["control", "catalog"]'
    greymatter.io/egress-tcp-local: '["wordpressdb"]'
spec:
  selector:
    matchLabels:
      greymatter.io/cluster: wordpressnew
      app: wordpressnew
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        greymatter.io/cluster: wordpressnew
        app: wordpressnew
        tier: frontend
    spec:
      containers:
      - image: wordpress:4.8-apache
        name: wordpress
        env:
        - name: WORDPRESS_DB_HOST
          value: 127.0.0.1:10912
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password
        ports:
        - containerPort: 80
          name: wordpress
        volumeMounts:
        - name: wordpressnew-persistent-storage
          mountPath: /var/`www/html
        resources:
          requests:
            memory: "256Mi"
            cpu: "660m"
          limits:
            memory: "256Mi"
            cpu: "1000m"
      volumes:
      - name: wordpressnew-persistent-storage
        persistentVolumeClaim:
          claimName: wp-new-pv-claim
